let myBioData = "I am Kabir Ahmed Ridoy";
// let sData= myBioData.search('Kabir');
// console.log(sData);
// let res= myBioData.slice(2,5);
// console.log(res);
// let replaceData = myBioData.replace("am", "Am");
// console.log(replaceData);
let str = "Hello World";
// let newStr = str.charAt(2);
let newStr= str.charCodeAt(4);
console.log(newStr);
